ol="SPOOLER_CSR_NO_PRINT_PROCESSOR_OR_DATA_TYPE" task="SPOOLER_TASK_CSR_REVERTING_TO_SSR" template="tid_SPOOLER_CSR_NO_PRINT_PROCESSOR_OR_DATA_TYPE" value="822" />
          <event channel="Admin" keywords="SPOOLER_KEYWORD" level="win:Informational" message="$(string.DEFAULT_PRINTER_CHANGED_EVENT)" opcode="SPOOLER_OPCODE_SUCCEEDED" symbol="DEFAULT_PRINTER_CHANGED_EVENT" task="SPOOLER_TASK_CHANGING_DEFAULT_PRINTER" template="tid_DEFAULT_PRINTER_CHANGED_EVENT" value="823" />
          <event channel="Operational" keywords="SPOOLER_KEYWORD_PIPELINE" level="win:Error" message="$(string.PRINT_FILTER_PIPELINE_SHUTDOWN_EVENT)" opcode="SPOOLER_OPCODE_FAILED" symbol="PRINT_FILTER_PIPELINE_SHUTDOWN_EVENT" task="SPOOLER_TASK_PIPELINE" template="tid_PRINT_FILTER_PIPELINE_SHUTDOWN_EVENT" value="824" />
          <event channel="Operational" keywords="SPOOLER_KEYWORD_CSR" level="win:Error" message="$(string.SPOOLER_CSR_FAILED_DONT_REVERT_TO_SSR)" opcode="SPOOLER_OPCODE_FAILED" symbol="SPOOLER_CSR_FAILED_DONT_REVERT_TO_SSR" task="SPOOLER_TASK_CSR_REVERTING_TO_SSR" template="tid_SPOOLER_CSR_FAILED_REVERT_TO_SSR" value="825" />
          <event channel="Operational" keywords="SPOOLER_KEYWORD_CSR" level="win:Informational" message="$(string.SPOOLER_CSR_FORCE_CSR_POLICY_SET)" opcode="SPOOLER_OPCODE_SUCCEEDED" symbol="SPOOLER_CSR_FORCE_CSR_POLICY_SET" task="SPOOLER_TASK_CSR_REVERTING_TO_SSR" template="tid_SPOOLER_CSR_FORCE_CSR_POLICY_SET" value="826" />
          <event channel="Operational" keywords="XPS_PRINT_API_KEYWORD" level="win:Error" message="$(string.XPS_PRINT_API_INVALID_QUEUE_EVENT)" opcode="XPS_PRINT_API_OPCODE_FAILED" symbol="XPS_PRINT_API_INVALID_QUEUE_EVENT" task="XPS_PRINT_API_TASK" template="tid_XPS_PRINT_API_INVALID_QUEUE_EVENT" value="827" />
          <event channel="Operational" keywords="XPS_PRINT_API_KEYWORD" level="win:Error" message="$(string.XPS_PRINT_API_JOB_FAILED_EVENT)" opcode="XPS_PRINT_API_OPCODE_FAILED" symbol="XPS_PRINT_API_JOB_FAILED_EVENT" task="XPS_PRINT_API_TASK" template="tid_XPS_PRINT_API_JOB_FAILED_EVENT" value="828" />
          <event channel="Debug" keywords="XPS_PRINT_API_KEYWORD_PERFORMANCE win:ResponseTime" level="win:Informational" message="$(string.XPS_PRINT_API_START_EVENT)" opcode="win:Start" symbol="XPS_PRINT_API_START_EVENT" task="XPS_PRINT_API_TASK_PERFORMANCE" template="tid_PRINT_PERFORMANCE" value="829" />
          <event channel="Debug" keywords="XPS_PRINT_API_KEYWORD_PERFORMANCE win:ResponseTime" level="win:Informational" message="$(string.XPS_PRINT_API_END_EVENT)" opcode="win:Stop" symbol="XPS_PRINT_API_END_EVENT" task="XPS_PRINT_API_TASK_PERFORMANCE" template="tid_PRINT_PERFORMANCE" value="830" />
          <event channel="Debug" keywords="XPS_PRINT_API_KEYWORD_PERFORMANCE win:ResponseTime" level="win:Informational" message="$(string.XPS_PRINT_API_DEPENDENCY_START_EVENT)" opcode="win:Start" symbol="XPS_PRINT_API_DEPENDENCY_START_EVENT" task="XPS_PRINT_API_TASK_PERFORMANCE" template="tid_PRINT_PERFORMANCE" value="831" />
          <event channel="Debug" keywords="XPS_PRINT_API_KEYWORD_PERFORMANCE win:ResponseTime" level="win:Informational" message="$(string.XPS_PRINT_API_DEPENDENCY_END_EVENT)" opcode="win:Stop" symbol="XPS_PRINT_API_DEPENDENCY_END_EVENT" task="XPS_PRINT_API_TASK_PERFORMANCE" template="tid_PRINT_PERFORMANCE" value="832" />
          <event channel="Debug" keywords="SPOOLER_KEYWORD win:ResponseTime" level="win:Informational" message="$(string.SPOOLER_OPERATION_START_EVENT)" opcode="win:Start" symbol="SPOOLER_OPERATION_START_EVENT" task="SPOOLER_TASK_PERFORMANCE" template="tid_PRINT_PERFORMANCE" value="833" />
          <event channel="Debug" keywords="SPOOLER_KEYWORD win:ResponseTime" level="win:Informational" message="$(string.SPOOLER_OPERATION_END_EVENT)" opcode="win:Stop" symbol="SPOOLER_OPERATION_END_EVENT" task="SPOOLER_TASK_PERFORMANCE" template="tid_PRINT_PERFORMANCE" value="834" />
          <event channel="Operational" keywords="SPOOLER_KEYWORD_PRINT_DRIVER_SANDBOX" level="win:Informational" message="$(string.PRINT_DRIVER_SANDBOX_JOB_PRINT_PROC_EVENT)" opcode="SPOOLER_OPCODE_SUCCEEDED" symbol="PRINT_DRIVER_SANDBOX_JOB_PRINT_PROC_EVENT" task="SPOOLER_TASK_PRINT_DRIVER_SANDBOX" template="tid_PRINT_DRIVER_SANDBOX_JOB_PRINT_PROC_EVENT" value="842" />
          <event channel="Debug" keywords="SPOOLER_KEYWORD_PRINT_DRIVER_SANDBOX" level="win:Informational" message="$(string.PRINT_DRIVER_SANDBOX_RPC_SUCCESS_EVENT)" opcode="SPOOLER_OPCODE_SUCCEEDED" symbol="PRINT_DRIVER_SANDBOX_RPC_SUCCESS_EVENT" task="SPOOLER_TASK_PRINT_DRIVER_SANDBOX" template="tid_PRINT_DRIVER_SANDBOX_RPC_SUCCESS_EVENT" value="843" />
          <event channel="Debug" keywords="SPOOLER_KEYWORD_PRINT_DRIVER_SANDBOX" level="win:Informational" message="$(string.PRINT_DRIVER_SANDBOX_MODE_SELECTION_EVENT)" opcode="SPOOLER_OPCODE_SUCCEEDED" symbol="PRINT_DRIVER_SANDBOX_MODE_SELECTION_EVENT" task="SPOOLER_TASK_PRINT_DRIVER_SANDBOX" template="tid_PRINT_DRIVER_SANDBOX_MODE_SELECTION_EVENT" value="844" />
          <event channel="Debug" keywords="SPOOLER_KEYWORD_PRINT_DRIVER_SANDBOX" level="win:Informational" message="$(string.PRINT_D